name : CICD ResumeBuilder On Organization Server

on:
  push:
    branches: 
     - main
jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v4
        with : 
           node-version : 'v18'
           
      # - run : npm ci
      # - run : unset CI && npm run build
      - run : touch "test.txt"

      - run : set CI = true
      - name: Deploy the build to server
        uses: srueda99/scp-action@v12
        with:
            port: 2202
            host: ${{ secrets.SERVER_HOST }}
            origin: "./test.txt"
            destination: "/var/www/resume-builder"
            username: ${{ secrets.SERVER_USER }}
            password: ${{ secrets.SERVER_PASS }}

