name : CICD ResumeBuilder On Organization Server

on:
  push:
    branches: 
     - main
jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v4
        with : 
           node-version : 'v18'
           
      - run : npm ci
      - run : unset CI && npm run build
      - run : ls

        
        
    
     
