name : CICD ResumeBuilder On Organization Server

on:
  push:
    branches: 
     - main
jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v4
        with : 
           node-version : 'v18'
           
      - run : npm ci
      - run : unset CI && npm run build
      
      - name: Deploy the build to server
        uses: cross-the-world/scp-pipeline@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASS }}
          local: "./build"
          remote: /var/www/resume-builder/
