name : CICD ResumeBuilder On Organization Server

on:
  push:
    branches: 
     - main
jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v4
        with : 
           node-version : 'v18'
           
      - run : npm ci
      - run : npm run build

      - name: Deploy build folder to remote server
        uses: srueda99/scp-action@v12
        with:
            port: 2202
            host: ${{ secrets.SERVER_ADDRESS }}
            origin: "./build"
            destination: "/var/html/resume-builder/"
            username: ${{ secrets.SERVER_USERNAME }}
            password: ${{ secrets.SERVER_PASSWORD }}

        
        
    
     
