name : CICD ResumeBuilder On Organization Server

on:
  push:
    branches: 
     - main
jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v2
      - uses : actions/setup-node@v4
        with : 
           node-version : 'v20'
           
      # - run : npm ci
      # - run : unset CI && npm run build
      - run : touch "test.txt"

      - run : set CI = true
      - name: Deploy the build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 2202
          source: "./test.txt"
          target: "/var/www/resume-builder"

