name : ResumeBuilder CI/CD

on:
  workflow_dispatch:
  push:
    branches: 
     - main
jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/resume-builder:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/resume-builder:latest
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          port: 2202
          script: |
            docker stop resume-builder
            docker run --name resume-builder -d -p 8000:80 ${{ secrets.DOCKERHUB_USERNAME }}/resume-builder:latest
